#!/bin/bash

asm_file="bootloader.asm"

if [ -n "$1" ]; then
  asm_file="$1"
fi

output_file="out/os.img"

mkdir -p out
nasm -f bin "$asm_file" -o "$output_file"
qemu-system-i386 -drive format=raw,file="$output_file"